package: yform_geo_osm
version: '1.2.3'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_geo_osm


requires:
    packages:
        yform/manager: '>=2,<4'

page:
    hidden: true

pages:
    yform/yform_geo_osm:
        title: 'Geo Osm'
