package: yform_geo_osm
version: '1.2.9'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_geo_osm

requires:
    packages:
        yform/manager: '>=2'
    redaxo: '^5.12'
    php:
        version: '>=7.2, <9'
page:
    hidden: true

pages:
    yform/yform_geo_osm:
        title: 'Geo Osm'
        perm: admin[]
