package: yform_geo_osm
version: '2.0.0-dev-2024-12-30'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_geo_osm

requires:
    packages:
        yform/manager: '>=2'
    redaxo: '^5.17'
    php:
        version: '>=8.0, <9'

page:
    title: 'Geo OSM'
    hidden: true

pages:
    yform/yform_geo_osm:
        title: 'Geo OSM'
        perm: admin[]
        icon: rex-icon fa-map-location-dot

default_config:
    geoapifykey: ''
