package: yform_geo_osm
version: '2.0.0-dev-2025-01-09'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_geo_osm

requires:
    packages:
        yform/manager: '>=4'
    redaxo: '^5.17'
    php:
        version: '>=8.0, <9'

pages:
    yform/manager/yform_geo_osm:
        title: 'translate:yform_geo_osm.batch_geocoding'
        perm: admin[]
        icon: rex-icon fa-map-location-dot

default_config:
    geoapifykey: ''
